### ISSUE TITLE
exec /app/scripts/init-nanit.sh: exec format error

### ISSUE THREAD

**Issue by M0LTE** [indiefan/home_assistant_nanit#18]
```
$ docker run -it -v /root/.docker-conf/nanit:/data --entrypoint=/app/scripts/init-nanit.sh indiefan/nanit
exec /app/scripts/init-nanit.sh: exec format error
$ uname -a
Linux services-pi-2 5.4.0-1115-raspi #127-Ubuntu SMP PREEMPT Wed Aug 7 14:38:47 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```

Anything I can do to assist?

**Comment by M0LTE** [comment]
Out of curiosity I just tried building the docker image from the Dockerfile, but the base image is... `indiefan/nanit` 😕 

and it also fails with `exec format error`

**Comment by cstraface** [comment]
Yeah I'm having the same issue. @M0LTE you're running on a Pi?

**Comment by absreda** [comment]
Same here - and yes, I'm running a Pi5

**Comment by absreda** [comment]
Nevermind...got it to work by running the script directly on the machine and copying the output file to the mounted /data folder.

Needed to install jq (apt-get install jq) to parse the json and change the path in the last line of the script to output the file in the right place.

**Comment by tonyjly** [comment]
Opened PR #19 with the proposed change to automatically install `jq` if it is missing.
