### ISSUE TITLE
Don't get email auth code

### ISSUE THREAD

**Issue by charliwest** [indiefan/home_assistant_nanit#2]
Trying this out and running `docker run -it -v /path/to/data:/data --entrypoint=/app/scripts/init-nanit.sh indiefan/nanit`

Fill in the info, but no email arrives. 
If I try and log into my account normally I get the sms or can request an email and that comes though ok. I tried then using that code but it also fails.

Logs show:-
`06 Nov 23 10:32 UTC INF Application started
06 Nov 23 10:32 UTC INF No .env file found. Using only environment variables path=/app/.env
06 Nov 23 10:32 UTC INF Setting log level to trace
06 Nov 23 10:32 UTC INF Loaded app session from the file filename=/data/session.json
06 Nov 23 10:32 UTC WRN Server responded with code 404. This typically means your refresh token has expired. Will try to login with username/password
06 Nov 23 10:32 UTC INF Authorizing using user credentials email= password=
06 Nov 23 10:32 UTC FTL Server responded with code 401. Provided credentials has not been accepted by the server. Please check if your e-mail address and password is entered correctly and that 2FA is disabled on your account.`

session.json looks like this:-
`{"revision":3,"authToken":null,"refreshToken":"null"}`

Any ideas what I might be doing wrong?

Thanks so much for picking up this project btw. It still beggars belief nanit has not made something like this available natively yet!

**Comment by charliwest** [comment]
I worked it out, seems the script doesn't like my old password, it had a ". _ *" in it, I changed to no special character and it works now.

**Comment by indiefan** [comment]
Ah, thanks for reporting this and working out what the root cause was. I'll look into proper escaping of user input in the init script.

**Comment by indiefan** [comment]
Okay, I tried to improve the input sanitization. Feel free to try it again and let me know if it runs into any issues. Dealing with strings in Bash is... not my favorite.

I also added a debug flag to the initialization script so you can get a little better idea of what it's doing (especially when/if it stumbles). It's a bit awkward in that you have to add the flag (`-d`) at the very end, so for example: `docker run -it -v /path/to/data:/data --entrypoint=/app/scripts/init-nanit.sh indiefan/nanit -d`

Anyways, thanks again for reporting the issue!
