### ISSUE TITLE
Sensor Data

### ISSUE THREAD

**Issue by jdsebo15** [indiefan/home_assistant_nanit#5]
Do you have plans for picking up the humidity and temperature sensor information?? Thanks a lot for doing this, you should throw a buy me a coffee link in the plugin for those that would like to contribute monetarily.

**Comment by indiefan** [comment]
I can look into this. I believe the pre-fork container handled this via mqtt (I never set it up personally, but tomorrow I'll look into whether or not that code is still functioning here).

Is that what you were thinking, or did you have something else in mind?

**Comment by jdsebo15** [comment]
Actually it looks like they may just need to be passed in as environment variables to docker compose. I’ll play with it today and let you know. Thank you for replying back! I’m pretty stoked about getting my Nanit into HomeKit. On Nov 10, 2023, at 00:39, Marke Hallowell ***@***.***> wrote:﻿
I can look into this. I believe the pre-fork container handled this via mqtt (I never set it up personally, but tomorrow I'll look into whether or not that code is still functioning here).
Is that what you were thinking, or did you have something else in mind?

**Comment by indiefan** [comment]
Yeah exactly, I just haven't checked to see if their still working or not after the fork. Let me know what you find out!

**Comment by jdsebo15** [comment]
It’s all still there. Just have to add the mqtt environment variables to docker compose and fire it up. If anyone in the future finds this, feel free to reach out to me for help.

**Comment by indiefan** [comment]
Thanks for looking into it and following up!
