### ISSUE TITLE
exec format error on running init-nanit.sh - raspberry pi

### ISSUE THREAD

**Issue by edlucky1** [indiefan/home_assistant_nanit#6]
When running init-nanit.sh, on raspberry pi, I get an "exec format error". 

I was getting other error with the initial fork, but the recent updates seem to have resolved it and now I get this error. Thanks! 

**Shell Script:**
`docker run -it -v ~/data:/data --entrypoint=/app/scripts/init-nanit.sh indiefan/nanit:latest`

**Raspberry Pi Error:**
`exec /app/scripts/init-nanit.sh: exec format error`

Initial research points towards a shebang related issue. First line of script has a space after shebang (not sure if this creates an issue?).

**Comment by indiefan** [comment]
Thanks for reporting this!

I tried removing the space and pushing a new release. Can you try and see if it resolves the issue for you?

If not, I may need some help (hard to fix something I can't reproduce...)

**Comment by edlucky1** [comment]
Just tried the latest version and same result. 

I dug a little further on the space after shebang issue and it seems to be a legacy problem that is resolved for most systems now.

I would be happy to test and provide details to help figure this one out. Will continue to research, but I am pretty inexperienced with coding.

**Comment by indiefan** [comment]
So my current best-guess is that one of two things is going on.

1) (unlikely) Your bash location is non-standard (can you do an `ls` to make sure that /bin/bash exists?)
2) (more likely) Your architecture isn't one of the ones supported by Docker's Buildx for Github (e.g. maybe 32-bit?). Can you run `uname -a` and let me know what it says?

**Comment by edlucky1** [comment]
1. `/usr/bin/bash` (I used `which bash`)

2. `Linux raspberrypi 6.1.0-rpi6-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.58-1+rpt2 (2023-10-27) aarch64 GNU/Linux`

**Comment by indiefan** [comment]
Hm. Maybe it's running the wrong image for your architecture? If you run `docker image inspect indiefan/nanit`, what does it say under "Architecture"? (it should be something like "arm64" or "arm64v7")

You could try pulling the image specifically for arm64 (e.g. `docker pull --platform linux/arm64 indiefan/nanit`) and then running that one.

**Comment by edlucky1** [comment]
The image that initially caused this error: `"Architecture": "arm", "Variant": "v7"`

Pulling image for platform linux/arm64: `"Architecture": "arm64"`

The pulled image now shows this error when running script: `WARNING: The requested image's platform (linux/arm64) does not match the detected host platform (linux/arm/v8) and no specific platform was requested
exec /app/scripts/init-nanit.sh: exec format error`

The warning about platforms was not there at the start of this issue. I believe this was previously resolved with multi platform work.

When I pull an image with no platform specified, the WARNING goes away but I still get exec format error: `exec /app/scripts/init-nanit.sh: exec format error`

**Comment by indiefan** [comment]
Ah okay. Try again with no platform (or with `--platform linux/arm/v8`)?

**Comment by edlucky1** [comment]
Pulling image with and without the platform linux/arm/v8 now results in `"Architecture": "arm", "Variant": "v8"`

The platform error doesn't come back, but still: 
`docker run -it -v ~/data:/data --entrypoint=/app/scripts/init-nanit.sh indiefan/nanit`
`exec /app/scripts/init-nanit.sh: exec format error`

**Comment by indiefan** [comment]
Oh wow, I did not expect the container to run fine. I guess the architecture issue was a red-herring.

Not sure if you want to continue debugging this. E.g. since you can bring up the container, attaching to it with `docker exec -it [container_name] /bin/bash` then trying a few things like executing the script from there (`/app/scripts/init-nanit.sh`, ensuring bash is present (although if the exec worked then I guess we know it is), and checking permissions for the script `ls -la /app/scripts/init-nanit.sh`).

That said, I totally understand if you're tired of looking into this and would rather just close the bug and move on with live. I'll leave it up to you!

**Comment by edlucky1** [comment]
I am onboard to keep running this down if you are! I learn best by fixing broken things haha. I'm sure others will run into this in the future. Since it does work now I may decrease the attention slightly, especially with the holidays coming up -- and this is my last week of paternity leave :(

Kiddo is asleep now, so I will continue in the morning when I don't need the container running.

Something I did find is that encoding can sometimes cause a similar issue: [Fixing exec format errors](https://nickjanetakis.com/blog/fixing-exec-format-errors-with-docker-entrypoint-scripts-on-windows)


Sidebar - are you planning to support this project long term? If so, I can help with some of the documentation (especially on homebridge & docker-compose which both seem out of date now). I just had a good update merged with the original project. I don't want to add a bunch of info if this project will become unsupported in the near future.

**Comment by edlucky1** [comment]
`docker exec -it [container_name] /bin/bash` results in:

`OCI runtime exec failed: exec failed: unable to start container process: exec /bin/bash: exec format error: unknown`

It may be worth noting that I am running the container via docker compose. Not sure if that changes how we think through this.

**Comment by indiefan** [comment]
Strange. Maybe your container just doesn't have bash?

Okay two things

1) I tried adding bash to the container explicitly to see if that would help. Can you pull the new image and try again (it should do this automatically, but just to make sure, use the latest tag, e.g. `docker pull indiefan/nanit:latest` before running)?

2) If it still doesn't work, can you try `docker exec -it [container_name] /bin/sh` and see if that fairs any better? If it does give you a shell, can you try editing the first line of `/app/scripts/init-nanit.sh` on the container to `#!/bin/sh` and then executing the script? I don't know enough about the difference between bash and sh to know if the script actually needs one vs the other (and i'm hesitant to deal with porting it/supporting multiple versions).

Thanks!

**Comment by indiefan** [comment]
Re: sidebar -- I am planning on supporting this for the foreseeable future! (that said, obviously I can't _guarantee_ anything)

I would gladly accept any contributions improving documentation!

**Comment by edlucky1** [comment]
Pulled latest image, same error when trying to run script from container.

I am unable to run /bin/bash or /bin/sh:

`OCI runtime exec failed: exec failed: unable to start container process: exec /bin/bash: exec format error: unknown`

**Comment by indiefan** [comment]
I'm so confused.

Are you able to exec into a shell for _any_ of the containers you run on that device? If so, can you send the "Architecture" output of `docker image inspect` for the container you can successfully execute a shell for?

**Comment by edlucky1** [comment]
Executing /bin/bash on my home assistant container works just fine.

Inspect:
`"Architecture": "arm",
        "Variant": "v7"`

**Comment by akeslo** [comment]
I'm joining the party :), I'm having the same issue on raspberry pi. 

I can't run the below command because I can't get the container running. It exists without username / password.  Additionally, I don't see any files in /app/scripts

> If it still doesn't work, can you try docker exec -it [container_name] /bin/sh and see if that fairs any better? If it does give you a shell, can you try editing the first line of /app/scripts/init-nanit.sh on the container to #!/bin/sh and then executing the script? I don't know enough about the difference between bash and sh to know if the script actually needs one vs the other (and i'm hesitant to deal with porting it/supporting multiple versions).

**Comment by Chetanladwa** [comment]
Hi - also having this issue on raspberry pi: exec format error.

Do you have any guidance to work round this / create the session.json? Apologies - this is now a bit beyond me...!

**Comment by edlucky1** [comment]
Marking stale

**Comment by edlucky1** [comment]
Marking stale
